springdoc:
  api-doc:
    path: /api-docs

mongodb:
  port: 27017
  dbname: dbdemo
  host: localhost

checkavailable:
  uri: http://maersk:com/api/bookings/checkAvailable

validation:
  origin:
    short: Origin is short
    long: Origin is long
  destination:
    short: Destination is short
    long: Destination is long
  quantity:
    minimum: Quantity is lesser than minimum
    maximum: Quantity is more than maximum

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
  error:
    include-message: always
  servlet:
   context-path: /demo
